### PR TITLE
Fixes for GCC 12

### PR DESCRIPTION
**Pull request by stephanosio**
This series includes the fixes for the GCC 12 / Zephyr SDK 0.15.0.

### CODE REVIEW

**Comment by sylvioalves** [comment]
@stephanosio How do you check all of these `forward declaration` if not manually? I can clean up if needed as well.

**Comment by stephanosio** [comment]
> @stephanosio How do you check all of these `forward declaration` if not manually? I can clean up if needed as well.

For the most part, `git grep 'IRAM_ATTR.*;'` should do.

**Comment by stephanosio** [comment]
@sylvioalves We will be switching to the Zephyr SDK 0.15.0 very soon and this is required for that. Could you review this first so we can proceed with that? You should be able to do more comprehensive clean-up of the `IRAM_ATTR` in the forward declarations after this is merged.

**Comment by sylvioalves** [comment]
@stephanosio, I have got this build output when adding those changes:  
```c

**Comment by sylvioalves** [comment]
@stephanosio I'll submit another PR removing forward declaration from a few other sources as well.

**Comment by stephanosio** [comment]
> I have got this build output when adding those changes. I haven't tried solving. Is that expected?

You need to use the [topic-sdk15 branch](https://github.com/zephyrproject-rtos/zephyr/tree/topic-sdk15) for now.

**Comment by sylvioalves** [comment]
> > I have got this build output when adding those changes. I haven't tried solving. Is that expected?
> 
> You need to use the [topic-sdk15 branch](https://github.com/zephyrproject-rtos/zephyr/tree/topic-sdk15) for now.

I have done that now. Seems it fixed previous build errors. Now I get this:  
```c
mponents/bootloader_support/src/bootloader_random.c
/home/sylvio/projects/espressif/zephyr/modules/hal/espressif/components/hal/esp32c3/include/hal/cpu_ll.h: Assembler messages:
/home/sylvio/projects/espressif/zephyr/modules/hal/espressif/components/hal/esp32c3/include/hal/cpu_ll.h:59: Error: unrecognized opcode `csrr t1,0x7e2'
/home/sylvio/projects/espressif/zephyr/modules/hal/espressif/components/hal/esp32c3/include/hal/cpu_ll.h:59: Error: unrecognized opcode `csrr a6,0x7e2'
```

**Comment by stephanosio** [comment]
> I have done that now. Seems it fixed previous build errors. Now I get this:

That is one of the things that this PR fixes:
https://github.com/zephyrproject-rtos/hal_espressif/pull/126/commits/81809d088e8f6c17c532f744cbd509ccc0a4b20c

**Comment by sylvioalves** [comment]
> > I have done that now. Seems it fixed previous build errors. Now I get this:
> 
> That is one of the things that this PR fixes: [81809d0](https://github.com/zephyrproject-rtos/hal_espressif/commit/81809d088e8f6c17c532f744cbd509ccc0a4b20c)

My bad, I switched branchs and lost that change. Working now.

**Comment by sylvioalves** [comment]
@stephanosio, tested. Confirmed working.

**Review by sylvioalves — APPROVED** [review]

**Comment by stephanosio** [comment]
> @stephanosio, tested. Confirmed working.

Thanks.

**Pull request merged**
