### PR TITLE
hal: esp32s3/esp32c3: add I2S support

### PR DESCRIPTION
**Pull request by wmrsouza**
added i2s support for esp32-s3 and esp32-c3

### CODE REVIEW

**Review by LucasTambor — COMMENTED** [review]
I think we should include the hal files and pincfg support only for S3 and C3. Since the support for other SoC won't be done right now

**Comment by sylvioalves** [comment]
Do we need to change/touch `i2s_legacy.c` file? It is not used.

**Review by raffarost — APPROVED** [review]

**Comment by wmrsouza** [comment]
> Do we need to change/touch `i2s_legacy.c` file? It is not used.

It really not used. I just mad
e changes to keep it compatible with modification made on `i2s_types.h` (to fix conflict with Zephyr types)

**Review by sylvioalves — APPROVED** [review]

**Comment by sylvioalves** [comment]
@LucasTambor PTAL

**Review by marekmatej — APPROVED** [review]

**Review by raffarost — APPROVED** [review]

**Pull request merged**
