### PR TITLE
west: add west installation

### PR DESCRIPTION
**Pull request by sylvioalves**
add esp-idf west python env environment

Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>

### CODE REVIEW

**Comment by sylvioalves** [comment]
@nashif, this fixes the issue you related.

**Comment by nashif** [comment]
> @nashif, this fixes the issue you related.

not clear why we have to install those python packages in a separate script and why we need to do this here. I already have west 8.0 installed. Looks like this install them in the system rather in the user folder?

Should we maybe just rely on what is maintain in zephyr, i.e. in the requirements.txt of zephyr and add the things needed for esp to the zephyr requirement?

**Comment by sylvioalves** [comment]
> > @nashif, this fixes the issue you related.
> 
> not clear why we have to install those python packages in a separate script and why we need to do this here. I already have west 8.0 installed. Looks like this install them in the system rather in the user folder?
> 
> Should we maybe just rely on what is maintain in zephyr, i.e. in the requirements.txt of zephyr and add the things needed for esp to the zephyr requirement?

@nashif, let me try to figure out another way to handle this if possible.

**Comment by sylvioalves** [comment]
@nashif, I have been checking at slack channel whether it is possible to add esp-idf python dependencies in `scripts/requirements-xx.txt`. However, I think it might mess user environment and possibly break esp-idf builds.

The reason esp-idf uses virtual env is to have it's proper package versioning x compatibility. 
At this moment, I having west package as part of virtual env is the way to go in my opinion.

Do you have any other suggestion?

Thanks.

**Comment by mahavirj** [comment]
@sylvioalves We can close this PR now, as we can work it around without using IDF py virtual env?

**Comment by sylvioalves** [comment]
Removed IDF python packages dependency for ESP32 Zephyr support.
This #5 fixs it.

**Pull request closed without merging**
