### PR TITLE
hal: esp32: pinctrl: add TWAI pinctrl support

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add pinctrl support for the Two-Wire Automotive Interface (TWAI) pins.

Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>

### CODE REVIEW

**Comment by sylvioalves** [comment]
@henrikbrixandersen Is it still draft?

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen Is it still draft?

I figured I'd finish the CAN driver first? But the pinctrl stuff seems to be working.

**Comment by henrikbrixandersen** [comment]
The pinctrl changes in this PR are complete. I will submit the CAN driver to Zephyr after the v3.1.0 feature freeze.

**Review by sylvioalves — APPROVED** [review]

**Comment by sylvioalves** [comment]
@henrikbrixandersen Do you think you can also include ESP32S2 and ESP32C3 TWAI pins as well?

**Comment by henrikbrixandersen** [comment]
@sylvioalves Are the TWAI IPs in the ESP32, ESP32S2, and ESP32C3 register compatible?

**Comment by sylvioalves** [comment]
> @sylvioalves Are the TWAI IPs in the ESP32, ESP32S2, and ESP32C3 register compatible?

If you use `hal` sources for your implementation, then it will handle automatically for all SoCs.  

https://github.com/zephyrproject-rtos/hal_espressif/blob/zephyr/components/hal/twai_hal.c  
https://github.com/zephyrproject-rtos/hal_espressif/blob/zephyr/components/hal/twai_hal_iram.c  
https://github.com/zephyrproject-rtos/hal_espressif/blob/zephyr/components/hal/include/hal/twai_hal.h

**Review by glaubermaroto — APPROVED** [review]

**Pull request merged**
